config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  resources :groupparticipants
  devise_for :users,:controllers=>{registrations:'registrations'}
  get 'home/mainPage' =>'home#mainPage'
  get 'home/index'=> 'home#index'
  post '/home/startchat'
  post '/home/invitecontact'
  post '/home/creategroup'
  get '/home/invitecontact'
  post '/home/sendmail'=>'home#sendmail'
  get 'home/personalChat'

end

app/models/group_description.rb
class GroupDescription < ActiveRecord::Base
end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :groupDescription



end

app/models/groupparticipant.rb
class Groupparticipant < ActiveRecord::Base
  belongs_to :user
  belongs_to :groupDescription








end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

   def user_name
   	
     return username;
   end     

   
  def  memberofgroup
    member = GroupMember.where(user_id: id).pluck(:groupDescription_id);  
    GroupDescription.where(id: member).pluck(:groupname);
  end

end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/groupparticipants_controller.rb
class GroupparticipantsController < ApplicationController
  before_action :set_groupparticipant, only: [:show, :edit, :update, :destroy]

  # GET /groupparticipants
  # GET /groupparticipants.json
  def index
    @groupparticipants = Groupparticipant.all
  end

  # GET /groupparticipants/1
  # GET /groupparticipants/1.json
  def show
  end

  # GET /groupparticipants/new
  def new
    @groupparticipant = Groupparticipant.new
  end

  # GET /groupparticipants/1/edit
  def edit
  end

  # POST /groupparticipants
  # POST /groupparticipants.json
  def create
    @groupparticipant = Groupparticipant.new(groupparticipant_params)

    respond_to do |format|
      if @groupparticipant.save
        format.html { redirect_to @groupparticipant, notice: 'Groupparticipant was successfully created.' }
        format.json { render :show, status: :created, location: @groupparticipant }
      else
        format.html { render :new }
        format.json { render json: @groupparticipant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groupparticipants/1
  # PATCH/PUT /groupparticipants/1.json
  def update
    respond_to do |format|
      if @groupparticipant.update(groupparticipant_params)
        format.html { redirect_to @groupparticipant, notice: 'Groupparticipant was successfully updated.' }
        format.json { render :show, status: :ok, location: @groupparticipant }
      else
        format.html { render :edit }
        format.json { render json: @groupparticipant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groupparticipants/1
  # DELETE /groupparticipants/1.json
  def destroy
    @groupparticipant.destroy
    respond_to do |format|
      format.html { redirect_to groupparticipants_url, notice: 'Groupparticipant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_groupparticipant
      @groupparticipant = Groupparticipant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def groupparticipant_params
      params.require(:groupparticipant).permit(:user_id, :groupDescription_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def mainPage 
  @chats= current_user.memberofgroup();	
  puts @chats,"hello";
  end

  def index
  end
  
  def startchat
  secPerson=params[:username];
  end

  def invitecontact
  end
  
  def sendmail
    for i in 1..4
  @user = params["friend#{i}"];
  u=User.where(username: @user)[0];
  # respond_to do |format|
  if u
     ProjectMailer.confirmation_email(@user).deliver     
   end
      # format.html { redirect_to @user, notice: 'User has confiremed request' }
      # # format.json { render :show, status: :created, location: @user }
    # else
    #   format.html { render :new }
    #   # format.json { render json: @user.errors, status: :unprocessable_entity }	
   end
   return redirect_to '/'
 end

  def personalChat
  personalchat = GroupDescription.new;
  personalchat.groupname= "Chat between "+current_user.username+"and"+params[:user];
  personalchat.save;
  u=User.where(username: params[:user])[0];
  user1=GroupMember.create(user_id: current_user.id,groupDescription_id: personalchat.id);
  user2=GroupMember.create(user_id: u.id,groupDescription_id: personalchat.id);
  redirect_to '/';
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController<Devise::RegistrationsController
	private 
	def sign_up_params
    params.require(:user).permit(:username,:mobileno,:birthday,:email, :password, :password_confirmation);
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groupparticipants_helper.rb
module GroupparticipantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/groupparticipants/_form.html.erb
<%= form_for(@groupparticipant) do |f| %>
  <% if @groupparticipant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@groupparticipant.errors.count, "error") %> prohibited this groupparticipant from being saved:</h2>

      <ul>
      <% @groupparticipant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :groupDescription_id %><br>
    <%= f.text_field :groupDescription_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groupparticipants/edit.html.erb
<h1>Editing Groupparticipant</h1>

<%= render 'form' %>

<%= link_to 'Show', @groupparticipant %> |
<%= link_to 'Back', groupparticipants_path %>

app/views/groupparticipants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groupparticipants</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Groupdescription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groupparticipants.each do |groupparticipant| %>
      <tr>
        <td><%= groupparticipant.user %></td>
        <td><%= groupparticipant.groupDescription %></td>
        <td><%= link_to 'Show', groupparticipant %></td>
        <td><%= link_to 'Edit', edit_groupparticipant_path(groupparticipant) %></td>
        <td><%= link_to 'Destroy', groupparticipant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Groupparticipant', new_groupparticipant_path %>

app/views/groupparticipants/new.html.erb
<h1>New Groupparticipant</h1>

<%= render 'form' %>

<%= link_to 'Back', groupparticipants_path %>

app/views/groupparticipants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @groupparticipant.user %>
</p>

<p>
  <strong>Groupdescription:</strong>
  <%= @groupparticipant.groupDescription %>
</p>

<%= link_to 'Edit', edit_groupparticipant_path(@groupparticipant) %> |
<%= link_to 'Back', groupparticipants_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>C</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
 <!--  <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/> -->
</head>
<body>
  <nav class="blue" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="#" class="brand-logo">Logo</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Navbar Link</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-lighten-2">Parallax Template</h1>
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
        <div class="row center">
          <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="background1.jpg"></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up development</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="background2.jpg"></div>
  </div>

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Contact Us</h4>
          <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="background3.jpg"></div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
   <!-- <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  // <script src="js/materialize.js"></script>
  // <script src="js/init.js"></script> -->

  </body>
</html>

app/views/home/invitecontact.html.erb
<!-- <!DOCTYPE html>
<html>
<head>
	<title>INVITE PAGE</title>
</head>
<body> -->
<div id="emailspage">   
<h1>INVITE FRIENDS TO CONNECT</h1>
<br>
<br>
<p>Add friends EMAIL ID to send request </p>
<form action="/home/sendmail" method="post">
<input type="text" name="friend1"><br><br>
<input type="text" name="friend2"><br><br>
<input type="text" name="friend3"><br><br>
<input type="submit" name="invite" value="send mail">
</form>
</div>
<!-- </body>
</html>
 -->

app/views/home/mainPage.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>MAIN PAGE</title>
</head>
<body>
<header>
<%= link_to "SignOut",destroy_user_session_path,method: :DELETE %>	
</header>
<main>
<section id="left">
<nav class="profile">
<div class="first">
<a>userImage</a>
</div>
<div class="second">
<h2><%= current_user.username %></h2>
<h3>status</h3>
</div>
</nav>

<nav class="chat">
<form action="home/startchat" method="POST">
<input type="text" name="username" value="Start a chat" >
</form>

<form action="home/invitecontact" method="POST">
<input type="submit" name="contact" value="Invite a Contact">
</form>

<form action="home/creategroup" method="POST">
<input type="submit" name="group" value="create a group">
</form>
</nav>


<% @chats.each do |member| %>
 <%= member %><br>
 <% end %>




</section>




<section id="middle">
 <nav id="inbetween">
 <div id="one">
 </div>
 <div id="two"></div>
 <div id="three"></div>
 <div id="four"></div>
 </nav>

</section>
<section id="right"></section>	


</main>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>